### PR TITLE
Deprecate ruby < 2.1

### PR DESCRIPTION
**Pull request by kris-lab**

### CODE REVIEW

**Comment by ppp0** [comment]
lgtm

**Comment by kris-lab** [comment]
@njam @ppp0 could you add me permission for merging?

**Comment by ppp0** [comment]
I'm not allowed to merge either, sorry

**Comment by njam** [comment]
now?

**Comment by kris-lab** [comment]
@njam thx!

**Comment by kris-lab** [comment]
released

**Pull request merged**
